// <auto-generated />
using System;
using GlobalIMCTask.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlobalIMCTask.Core.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20210331143638_db-edit")]
    partial class dbedit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("GlobalIMCTask.Core.Models.DietaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("DietaryTypes");
                });

            modelBuilder.Entity("GlobalIMCTask.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GlobalIMCTask.Core.Models.DietaryType", b =>
                {
                    b.HasOne("GlobalIMCTask.Core.Models.Product", null)
                        .WithMany("DietaryTypes")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("GlobalIMCTask.Core.Models.Product", b =>
                {
                    b.Navigation("DietaryTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
